/*
 * Golang Gin Openapi API
 *
 * Here is golang-gin-openapi API project.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package server

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// Health - health API
func Health(c *gin.Context) {
	res := &HealthCheckModel{
		Result: "success",
	}
	c.JSON(http.StatusOK, res)
}
