/*
 * Golang Gin Openapi API
 *
 * Here is golang-gin-openapi API project.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package model

// ErrorModel -
type ErrorModel struct {
	ReasonCode string `json:"reasonCode,omitempty"`

	ReasonDetailMessage string `json:"reasonDetailMessage,omitempty"`
}
