/*
 * Golang Gin Openapi API
 *
 * Here is golang-gin-openapi API project.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package model

// HealthCheckModel -
type HealthCheckModel struct {
	Result string `json:"result"`
}
